load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "calculator",
    srcs = ["calculator.cc"],
    hdrs = ["calculator.h"],
    visibility = ["//main:__pkg__", "//test:__pkg__"],
)

cc_library(
    name = "greeter",
    srcs = ["greeter.cc"],
    hdrs = ["greeter.h"],
    visibility = ["//main:__pkg__", "//test:__pkg__"],
)
